(function(d){var a=function(a,b){"undefined"==typeof b&&(b={});this.init(a,b)},b=a.prototype,c,o=["canvas","vml"],f=["oval","spiral","square","rect","roundRect"],v=/^\#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$/,z=-1!==navigator.appVersion.indexOf("MSIE")&&8===parseFloat(navigator.appVersion.split("MSIE")[1])?!0:!1,s=!!document.createElement("canvas").getContext,n=!0,w=function(a,b,c){var a=document.createElement(a),t;for(t in c)a[t]=c[t];"undefined"!==typeof b&&b.appendChild(a);return a},t=function(a,b){for(var c in b)a.style[c]=
b[c];return a},y=function(a,b){for(var c in b)a.setAttribute(c,b[c]);return a},F=function(a,b,c,t){a.save();a.translate(b,c);a.rotate(t);a.translate(-b,-c);a.beginPath()};b.init=function(b,r){if("boolean"===typeof r.safeVML)n=r.safeVML;try{this.mum=void 0!==document.getElementById(b)?document.getElementById(b):document.body}catch(d){this.mum=document.body}r.id="undefined"!==typeof r.id?r.id:"canvasLoader";this.cont=w("div",this.mum,{id:r.id});if(s)c=o[0],this.can=w("canvas",this.cont),this.con=this.can.getContext("2d"),
this.cCan=t(w("canvas",this.cont),{display:"none"}),this.cCon=this.cCan.getContext("2d");else{c=o[1];if("undefined"===typeof a.vmlSheet){document.getElementsByTagName("head")[0].appendChild(w("style"));a.vmlSheet=document.styleSheets[document.styleSheets.length-1];var e=["group","oval","roundrect","fill"],g;for(g in e)a.vmlSheet.addRule(e[g],"behavior:url(#default#VML); position:absolute;")}this.vml=w("group",this.cont)}this.setColor(this.color);this.draw();t(this.cont,{display:"none"})};b.cont={};
b.can={};b.con={};b.cCan={};b.cCon={};b.timer={};b.activeId=0;b.diameter=40;b.setDiameter=function(a){this.diameter=Math.round(Math.abs(a));this.redraw()};b.getDiameter=function(){return this.diameter};b.cRGB={};b.color="#000000";b.setColor=function(a){this.color=v.test(a)?a:"#000000";this.cRGB=this.getRGB(this.color);this.redraw()};b.getColor=function(){return this.color};b.shape=f[0];b.setShape=function(a){for(var b in f)if(a===f[b]){this.shape=a;this.redraw();break}};b.getShape=function(){return this.shape};
b.density=40;b.setDensity=function(a){this.density=n&&c===o[1]?40>=Math.round(Math.abs(a))?Math.round(Math.abs(a)):40:Math.round(Math.abs(a));if(360<this.density)this.density=360;this.activeId=0;this.redraw()};b.getDensity=function(){return this.density};b.range=1.3;b.setRange=function(a){this.range=Math.abs(a);this.redraw()};b.getRange=function(){return this.range};b.speed=2;b.setSpeed=function(a){this.speed=Math.round(Math.abs(a))};b.getSpeed=function(){return this.speed};b.fps=24;b.setFPS=function(a){this.fps=
Math.round(Math.abs(a));this.reset()};b.getFPS=function(){return this.fps};b.getRGB=function(a){a="#"===a.charAt(0)?a.substring(1,7):a;return{r:parseInt(a.substring(0,2),16),g:parseInt(a.substring(2,4),16),b:parseInt(a.substring(4,6),16)}};b.draw=function(){var a=0,b,d,e,g,i,s,x,n=this.density,v=Math.round(n*this.range),l,h,G=0;h=this.cCon;var m=this.diameter;if(c===o[0]){h.clearRect(0,0,1E3,1E3);y(this.can,{width:m,height:m});for(y(this.cCan,{width:m,height:m});a<n;){l=a<=v?1-1/v*a:l=0;s=270-360/
n*a;x=s/180*Math.PI;h.fillStyle="rgba("+this.cRGB.r+","+this.cRGB.g+","+this.cRGB.b+","+l.toString()+")";switch(this.shape){case f[0]:case f[1]:b=0.07*m;g=0.47*m+Math.cos(x)*(0.47*m-b)-0.47*m;i=0.47*m+Math.sin(x)*(0.47*m-b)-0.47*m;h.beginPath();this.shape===f[1]?h.arc(0.5*m+g,0.5*m+i,b*l,0,2*Math.PI,!1):h.arc(0.5*m+g,0.5*m+i,b,0,2*Math.PI,!1);break;case f[2]:b=0.12*m;g=Math.cos(x)*(0.47*m-b)+0.5*m;i=Math.sin(x)*(0.47*m-b)+0.5*m;F(h,g,i,x);h.fillRect(g,i-0.5*b,b,b);break;case f[3]:case f[4]:d=0.3*
m,e=0.27*d,g=Math.cos(x)*(e+0.13*(m-e))+0.5*m,i=Math.sin(x)*(e+0.13*(m-e))+0.5*m,F(h,g,i,x),this.shape===f[3]?h.fillRect(g,i-0.5*e,d,e):(b=0.55*e,h.moveTo(g+b,i-0.5*e),h.lineTo(g+d-b,i-0.5*e),h.quadraticCurveTo(g+d,i-0.5*e,g+d,i-0.5*e+b),h.lineTo(g+d,i-0.5*e+e-b),h.quadraticCurveTo(g+d,i-0.5*e+e,g+d-b,i-0.5*e+e),h.lineTo(g+b,i-0.5*e+e),h.quadraticCurveTo(g,i-0.5*e+e,g,i-0.5*e+e-b),h.lineTo(g,i-0.5*e+b),h.quadraticCurveTo(g,i-0.5*e,g+b,i-0.5*e))}h.closePath();h.fill();h.restore();++a}}else{t(this.cont,
{width:m,height:m});t(this.vml,{width:m,height:m});switch(this.shape){case f[0]:case f[1]:x="oval";b=140;break;case f[2]:x="roundrect";b=120;break;case f[3]:case f[4]:x="roundrect",b=300}d=e=b;g=500-e;for(i=0.5*-e;a<n;){l=a<=v?1-1/v*a:l=0;s=270-360/n*a;switch(this.shape){case f[1]:d=e=b*l;g=500-0.5*b-0.5*b*l;i=0.5*(b-b*l);break;case f[0]:case f[2]:z&&(i=0,this.shape===f[2]&&(g=500-0.5*e));break;case f[3]:case f[4]:d=0.95*b,e=0.28*d,z?(g=0,i=500-0.5*e):(g=500-d,i=0.5*-e),G=this.shape===f[4]?0.6:0}h=
y(t(w("group",this.vml),{width:1E3,height:1E3,rotation:s}),{coordsize:"1000,1000",coordorigin:"-500,-500"});h=t(w(x,h,{stroked:!1,arcSize:G}),{width:d,height:e,top:i,left:g});w("fill",h,{color:this.color,opacity:l});++a}}this.tick(!0)};b.clean=function(){if(c===o[0])this.con.clearRect(0,0,1E3,1E3);else{var a=this.vml;if(a.hasChildNodes())for(;1<=a.childNodes.length;)a.removeChild(a.firstChild)}};b.redraw=function(){this.clean();this.draw()};b.reset=function(){"number"===typeof this.timer&&(this.hide(),
this.show())};b.tick=function(a){var b=this.con,d=this.diameter;a||(this.activeId+=360/this.density*this.speed);c===o[0]?(b.clearRect(0,0,d,d),F(b,0.5*d,0.5*d,this.activeId/180*Math.PI),b.drawImage(this.cCan,0,0,d,d),b.restore()):(360<=this.activeId&&(this.activeId-=360),t(this.vml,{rotation:this.activeId}))};b.show=function(){if("number"!==typeof this.timer){var a=this;this.timer=self.setInterval(function(){a.tick()},Math.round(1E3/this.fps));t(this.cont,{display:"block"})}};b.hide=function(){"number"===
typeof this.timer&&(clearInterval(this.timer),delete this.timer,t(this.cont,{display:"none"}))};b.kill=function(){var a=this.cont;"number"===typeof this.timer&&this.hide();c===o[0]?(a.removeChild(this.can),a.removeChild(this.cCan)):a.removeChild(this.vml);for(var b in this)delete this[b]};d.CanvasLoader=a})(window);
function PxLoader(d){d=d||{};if(null==d.statusInterval)d.statusInterval=5E3;if(null==d.loggingDelay)d.loggingDelay=2E4;if(null==d.noProgressTimeout)d.noProgressTimeout=Infinity;var a=[],b=[],c,o=+new Date,f=function(a){return null==a?[]:Array.isArray(a)?a:[a]};this.add=function(b){b.tags=f(b.tags);if(null==b.priority)b.priority=Infinity;a.push({resource:b,state:0})};this.addProgressListener=function(a,c){b.push({callback:a,tags:f(c)})};this.addCompletionListener=function(a,c){b.push({tags:f(c),callback:function(b){b.completedCount===
b.totalCount&&a()}})};var v=function(a){var a=f(a),b=function(b){for(var b=b.resource,c=Infinity,d=0,y=b.tags.length;d<y;d++){var e=a.indexOf(b.tags[d]);0<=e&&e<c&&(c=e)}return c};return function(a,c){var d=b(a),t=b(c);return d<t?-1:d>t?1:a.priority<c.priority?-1:a.priority>c.priority?1:0}};this.start=function(b){c=+new Date;b=v(b);a.sort(b);for(var b=0,d=a.length;b<d;b++){var f=a[b];f.status=1;f.resource.start(this)}setTimeout(z,100)};var z=function(){for(var b=!1,c=+new Date-o,f=c>=d.noProgressTimeout,
c=c>=d.loggingDelay,s=0,r=a.length;s<r;s++){var n=a[s];if(1===n.status&&(n.resource.checkStatus(),1===n.status))if(f)n.resource.onTimeout();else b=!0}c&&b&&w();b&&setTimeout(z,d.statusInterval)};this.isBusy=function(){for(var b=0,c=a.length;b<c;b++)if(0===a[b].status||1===a[b].status)return!0;return!1};var s=function(a,b){for(var c=0,d=a.length;c<d;c++)if(0<=b.indexOf(a[c]))return!0;return!1},n=function(c,d){for(var f=null,n=0,r=a.length;n<r;n++)if(a[n].resource===c){f=a[n];break}if(!(null==f||1!==
f.status)){f.status=d;o=+new Date;n=0;for(r=b.length;n<r;n++){var w=b[n];if(0===w.tags.length||s(c.tags,w.tags)){for(var e=f,g=0,i=0,v=0,x=a.length;v<x;v++){var z=a[v];if(0===w.tags.length||s(z.resource.tags,w.tags))i++,(2===z.status||3===z.status||4===z.status)&&g++}w.callback({resource:e.resource,loaded:2===e.status,error:3===e.status,timeout:4===e.status,completedCount:g,totalCount:i})}}}};this.onLoad=function(a){n(a,2)};this.onError=function(a){n(a,3)};this.onTimeout=function(a){n(a,4)};var w=
this.log=function(b){if(window.console){var d=Math.round((+new Date-c)/1E3);window.console.log("PxLoader elapsed: "+d+" sec");for(var d=0,f=a.length;d<f;d++){var n=a[d];if(b||1===n.status){var r="PxLoader: #"+d+" "+n.resource.getName();switch(n.status){case 0:r+=" (Not Started)";break;case 1:r+=" (Waiting)";break;case 2:r+=" (Loaded)";break;case 3:r+=" (Error)";break;case 4:r+=" (Timeout)"}0<n.resource.tags.length&&(r+=" Tags: ["+n.resource.tags.join(",")+"]");window.console.log(r)}}}}}
if(!Array.isArray)Array.isArray=function(d){return"[object Array]"==Object.prototype.toString.call(d)};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(d){if(null==this)throw new TypeError;var a=Object(this),b=a.length>>>0;if(0===b)return-1;var c=0;0<arguments.length&&(c=Number(arguments[1]),c!=c?c=0:0!=c&&Infinity!=c&&-Infinity!=c&&(c=(0<c||-1)*Math.floor(Math.abs(c))));if(c>=b)return-1;for(c=0<=c?c:Math.max(b-Math.abs(c),0);c<b;c++)if(c in a&&a[c]===d)return c;return-1};
function PxLoaderImage(d,a,b){var c=this,o=null;this.img=new Image;this.tags=a;this.priority=b;var f=function(){"complete"==c.img.readyState&&(s(),o.onLoad(c))},v=function(){s();o.onLoad(c)},z=function(){s();o.onError(c)},s=function(){c.unbind("load",v);c.unbind("readystatechange",f);c.unbind("error",z)};this.start=function(a){o=a;c.bind("load",v);c.bind("readystatechange",f);c.bind("error",z);c.img.src=d};this.checkStatus=function(){c.img.complete&&(s(),o.onLoad(c))};this.onTimeout=function(){s();
if(c.img.complete)o.onLoad(c);else o.onTimeout(c)};this.getName=function(){return d};this.bind=function(a,b){c.img.addEventListener?c.img.addEventListener(a,b,!1):c.img.attachEvent&&c.img.attachEvent("on"+a,b)};this.unbind=function(a,b){c.img.removeEventListener?c.img.removeEventListener(a,b,!1):c.img.detachEvent&&c.img.detachEvent("on"+a,b)}}PxLoader.prototype.addImage=function(d,a,b){d=new PxLoaderImage(d,a,b);this.add(d);return d.img};if("undefined"===typeof window.wyx)window.wyx={};
if("undefined"===typeof window.wyx.h5game)window.wyx.h5game={};
wyx.h5game.getPageSize=function(){var d,a,b,c;window.innerHeight&&window.scrollMaxY?(d=document.body.scrollWidth,a=window.innerHeight+window.scrollMaxY):document.body.scrollHeight>document.body.offsetHeight?(d=document.body.scrollWidth,a=document.body.scrollHeight):(d=document.body.offsetWidth,a=document.body.offsetHeight);if(self.innerHeight)b=self.innerWidth,c=self.innerHeight;else if(document.documentElement&&document.documentElement.clientHeight)b=document.documentElement.clientWidth,c=document.documentElement.clientHeight;
else if(document.body)b=document.body.clientWidth,c=document.body.clientHeight;return[d<b?b:d,a<c?c:a,b,c]};wyx.h5game.isEventSupported=function(){var d={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(a){var b=document.createElement(d[a]||"div"),a="on"+a,c=a in b;c||(b.setAttribute(a,"return;"),c="function"===typeof b[a]);return c}}();
wyx.h5game.extend=function(d){[].slice.call(arguments,1).forEach(function(a){for(var b in a)d[b]=a[b]});return d};
(function(d){function a(c){this.isLock=!1;wyx.h5game.extend(this,b,c);this.diffY=Math.ceil(this.height*(a.sh/a.sw-1));this.y+=this.diffY*this.row;this.dropHeight=0}var b={x:0,y:0,width:45,height:45,row:0,col:0,img:null,ctx:null};a.sw=90;a.sh=96;a.animalNum=6;a.getRandom=function(b){var d=parseInt(Math.random()*a.animalNum,10);return d===b?(d+1)%a.animalNum:d};a.prototype={show:function(){this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],this.x,this.y,this.width,this.height+this.diffY)},destroy:function(){this.ctx.clearRect(this.x,
this.y,this.width,this.height+this.diffY)},update:function(){if(this.isLock)if(this.ctx.clearRect(this.x,this.y,this.width,this.height+this.diffY),0<this.dropHeight){this.dropHeight-=this.dropDiffHeight;if(0>=this.dropHeight)this.isLock=!1,this.dropHeight=0;this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],this.x,this.y-this.dropHeight,this.width,this.height+this.diffY)}else if(this.scale)this.scale+=4,this.scale<this.width/2?this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],this.x+this.scale,
this.y+this.scale,this.width-2*this.scale,this.height-2*this.scale+this.diffY):(this.scale=0,this.img=[a.getRandom(this.img[0]),1],this.magnify=parseInt(this.width/4,10));else if(this.shake){this.shake-=1;var b=0===this.shake%2?-1:1;0<this.shake?this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],this.x+b,this.y+b,this.width,this.height+this.diffY):(this.shake=0,this.animScale())}else if(this.magnify){this.magnify-=2;if(0>this.magnify)this.magnify=0;this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],
this.x+this.magnify/2,this.y+this.magnify/2,this.width-this.magnify,this.height-this.magnify+this.diffY);if(0===this.magnify)this.isLock=!1}else{if(this.mouse)if(0>=this.mouse.repeat)b=a.prototype[this.mouse.direct].call(this),this.isLock=!1,b?b.animMouse(this.mouse.direct,this.mouse.callback):this.mouse.callback.call(this),this.mouse=null;else if(this.ctx.drawImage("bottom"==this.mouse.direct?a.mouseImgArr[this.mouse.step]:a.frogImgArr[this.mouse.step],this.x,this.y,this.width,this.height+this.diffY),
this.mouse.step++,3<=this.mouse.step)this.mouse.repeat--,this.mouse.step=0}else if(this.star)this.star.count<=this.star.max?(this.ctx.clearRect(this.x,this.y,this.width,this.height+this.diffY),this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],this.x,this.y,this.width,this.height+this.diffY),this.ctx.drawImage(a.starsArr[this.star.count],this.x,this.y,this.width,this.height+this.diffY),this.star.count+=this.star.step):(this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],this.x,this.y,this.width,
this.height+this.diffY),this.star.callback&&this.star.callback(),this.star=null);else if(this.boom)this.boom.count<=this.boom.max?(this.ctx.clearRect(this.x,this.y,this.width,this.height+this.diffY),this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],this.x,this.y,this.width,this.height+this.diffY),this.ctx.drawImage(a.boomArr[this.boom.count%2],this.x,this.y,this.width+this.boom.max-this.boom.count,this.height+this.diffY+this.boom.max-this.boom.count),this.boom.count+=this.boom.step):(this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],
this.x,this.y,this.width,this.height+this.diffY),this.boom.callback&&this.boom.callback(),this.boom=null);else if(this.booming)this.booming.count<=this.booming.max?(this.ctx.clearRect(this.x,this.y,this.width,this.height+this.diffY),this.booming.count>this.booming.startBoomed?this.ctx.drawImage(a.boomed,this.x,this.y,this.width,this.height+this.diffY):this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],this.x,this.y,this.width,this.height+this.diffY),this.booming.count<=this.booming.boomingMax&&
this.ctx.drawImage(a.boomingArr[parseInt(this.booming.count,10)],this.x,this.y,this.width,this.height+this.diffY),this.booming.count+=this.booming.step):(this.booming.callback&&this.booming.callback(),this.booming=null);else if(this.bigboom)this.bigboom.count<=this.bigboom.max?(this.ctx.clearRect(this.x,this.y,this.width,this.height+this.diffY),this.ctx.drawImage(a.bigboomArr[this.bigboom.count%2],this.x,this.y,this.width,this.height+this.diffY),this.bigboom.count+=this.bigboom.step):(this.bigboom.callback&&
this.bigboom.callback(),this.bigboom=null);else if(this.disappear)this.disappear.count<this.disappear.max?(this.ctx.clearRect(this.x,this.y,this.width,this.height+this.diffY),this.ctx.drawImage(a.disappearArr[this.disappear.count],this.x,this.y,this.width,this.height+this.diffY),this.disappear.count+=this.disappear.step):(this.disappear.callback&&this.disappear.callback(),this.disappear=null);else if(this.isRedraw)this.ctx.clearRect(this.x,this.y,this.width,this.height+this.diffY),this.ctx.drawImage(a.imgArr[this.img[0]][this.img[1]],
this.x,this.y,this.width,this.height+this.diffY),this.isRedraw=!1},setRedraw:function(){this.isRedraw=!0},animScale:function(){this.isLock=!0;this.scale=1},animDrop:function(a){this.isLock=!0;this.dropDiffHeight=parseInt(this.height/4,10);this.dropCallBack=a},animMouse:function(a,b){this.isLock=!0;this.mouse={direct:a,repeat:1,callback:b,step:0}},animStar:function(a){this.star={count:1,max:15,step:1,callback:a}},animBoom:function(a){this.boom={count:1,max:15,step:1,callback:a}},animBooming:function(a){this.booming=
{count:0,max:9,boomingMax:6,startBoomed:3,step:0.5,callback:a}},animBigboom:function(a){this.bigboom={count:1,max:15,step:1,callback:a}},animDisappear:function(a){this.disappear={count:1,max:11,step:1,callback:a}},animShake:function(){this.isLock=!0;this.shake=20},setState:function(a){this.img[1]=a},getState:function(){return this.img[1]},setImgIndex:function(a){this.img[0]=a},getImgIndex:function(){return this.img[0]},getLock:function(){return this.isLock},top:function(){return 0<=this.row-1?a.cells[this.row-
1][this.col]:null},bottom:function(){return 7>this.row+1?a.cells[this.row+1][this.col]:null},left:function(){return 0<=this.col-1?a.cells[this.row][this.col-1]:null},right:function(){return 7>this.col+1?a.cells[this.row][this.col+1]:null}};d.Cell=a})(window);
(function(d){var a,b;function c(a){for(var b=0;b<h;b++){a[b]=[];for(var c=0;c<h;c++)a[b][c]=0}}function o(a){var b=a.pageX,c=a.pageY;if("touchstart"===a.type||"touchend"===a.type)b=a.touches[0].pageX,c=a.touches[0].pageY;for(var a=a.target,j=a.offsetTop,d=a.offsetLeft;a=a.offsetParent;)j+=a.offsetTop,d+=a.offsetLeft;return{x:b-d,y:c-j}}function f(a){return Cell.cells[Math.floor(a.y/(B+Cell.cells[0][0].diffY))][Math.floor(a.x/B)]}function v(a){a=a||60;return d.requestAnimationFrame||d.mozRequestAnimationFrame||
d.webkitRequestAnimationFrame||d.msRequestAnimationFrame||d.oRequestAnimationFrame||function(b){d.setTimeout(b,1E3/a)}}function z(){for(var a=Cell.cells.length,b=0;b<a;b++)for(var c=Cell.cells[b].length,j=0;j<c;j++)if(Cell.cells[b][j].getLock())return!0;return!1}function s(a,b){var c=[],j,d,q;c.push(a);m[a.row][a.col]=1;if(a.row+1<h&&2!==b)j=a.row+1,d=a.col,q=Cell.cells[j][d],!q.getLock()&&q.getImgIndex()===a.getImgIndex()&&0===m[j][d]&&(c=c.concat(s(q,0)));if(a.col+1<h&&1!==b)j=a.row,d=a.col+1,q=
Cell.cells[j][d],!q.getLock()&&q.getImgIndex()===a.getImgIndex()&&0===m[j][d]&&(c=c.concat(s(q,3)));if(0<=a.row-1&&0!==b)j=a.row-1,d=a.col,q=Cell.cells[j][d],!q.getLock()&&q.getImgIndex()===a.getImgIndex()&&0===m[j][d]&&(c=c.concat(s(q,2)));if(0<=a.col-1&&3!==b)j=a.row,d=a.col-1,q=Cell.cells[j][d],!q.getLock()&&q.getImgIndex()===a.getImgIndex()&&0===m[j][d]&&(c=c.concat(s(q,1)));return c}function n(){c(L);for(var a=Cell.cells.length,b,d=0;d<a;d++)for(var j=Cell.cells[d].length,k=0;k<j;k++)if(c(m),
b=s(Cell.cells[d][k]),L[d][k]=b.length,2<L[d][k])return!1;return!0}function w(a){for(var b,c,d,k,q,e,a=a||2,f=0;f<a;f++)d=0,b=parseInt(Math.random()*h,10),c=parseInt(Math.random()*h,10),e=Cell.cells[b][c],b=e.top(),c=e.left(),k=e.right(),q=e.bottom(),2>d&&b&&(b.img[0]=e.img[0],b.img[1]=e.img[1],b.setRedraw(),d++),2>d&&k&&(k.img[0]=e.img[0],k.img[1]=e.img[1],k.setRedraw(),d++),2>d&&q&&(q.img[0]=e.img[0],q.img[1]=e.img[1],q.setRedraw(),d++),2>d&&c&&(c.img[0]=e.img[0],c.img[1]=e.img[1],c.setRedraw())}
function t(a){var b=parseInt(a/1E4),a=parseInt(a/1E3%10);0==b&&1==a%2?(I[0].className="time_bg time_num_"+b+"_red",I[1].className="time_bg time_num_"+a+"_red"):(I[0].className="time_bg time_num_"+b,I[1].className="time_bg time_num_"+a)}function y(b){if(b)a.toolsWarning.push(function(){document.getElementById("messagebox_tool").style.background="url('img/item/"+b.img+".png') no-repeat";document.getElementById("messagebox_tool_text").innerHTML=b.text}),y();else if(a.toolsEventIndex<a.toolsWarning.length&&
(document.getElementById("div_messagebox").style.display="block",document.getElementById("control_panel").style.opacity="0.3",1!=a.toolAlerting))a.toolsWarning[a.toolsEventIndex]()}function F(b){document.getElementById("control_panel").style.opacity="0.3";document.getElementById("messagebox_tool").style.background="url('img/item/"+b.img+".png') no-repeat";document.getElementById("messagebox_tool_text").innerHTML=b.text;document.getElementById("div_messagebox").style.display="block";document.getElementById("control_panel").style.opacity=
"0.3";a.toolAlerting=1;setTimeout(function(){document.getElementById("div_messagebox").style.display="none";document.getElementById("control_panel").style.opacity="1";a.toolAlerting=0;y()},1E3);y()}function R(a){if(T!=a)if(T=a,0>=a)M.innerHTML="<span class='score_bg score_num_0'></span>";else{for(var b="<span class='score_bg score_num_"+parseInt(a%10)+"'></span>",c=10,d=parseInt(a/c);d;)b="<span class='score_bg score_num_"+d%10+"'></span>"+b,c*=10,d=parseInt(a/c);M.innerHTML=b}}function r(a){a?(document.getElementById("screen_resume_diffheight_div").style.display=
"block",document.getElementById("resume").style.display="block",document.getElementById("screen_prize_span").style.display="none"):(document.getElementById("screen_resume_diffheight_div").style.display="none",document.getElementById("resume").style.display="none",document.getElementById("screen_prize_span").style.display="block",document.getElementById("final_score_div").innerHTML=document.getElementById("span_score").innerHTML);U()}function S(){document.querySelector("header").style.display="block";
document.getElementById("main").style.display="block";document.querySelector(".entrance").style.display="none"}function e(a){var b=wyx.h5game.getPageSize(),c;N=u.getContext("2d");c=Math.min(b[0],b[1]);Math.max(b[0],b[1]);c=320;B=45;u.width=B*h;u.height=u.width+B*(Cell.sh/Cell.sw-1)*h;var j=u.width,k=u.height;u.width=j*d.devicePixelRatio;u.height=k*d.devicePixelRatio;u.style.width=j+"px";u.style.height=k+"px";N.scale(d.devicePixelRatio,d.devicePixelRatio);j=b[1]-u.height;j=57;u.style.marginTop=j+"px";
k=document.querySelector("header");k.style.height=j+"px";k.style.visibility="visible";I=document.querySelectorAll(".time_bg");M=document.getElementById("span_score");O=document.getElementById("div_messagebox");O.style.left=document.getElementById("span_messagebox").offsetLeft+"px";O.style.top=document.getElementById("span_messagebox").offsetTop-4+"px";E.dom=document.getElementById("div_screen");E.dom.style.left=document.getElementById("control_panel").offsetLeft+"px";E.dom.style.top=j-E.height+"px";
E.dom.style.display="block";U=function(a,b,c){return function(){c.clearTimeout(a.uping);-16>parseInt(a.dom.style.top)?(a.dom.style.top=parseInt(a.dom.style.top)+16+"px",a.downing=setTimeout(arguments.callee,5)):a.dom.style.top="0px"}}(E,j,d);K=function(a,b,c){return function(){c.clearTimeout(a.downing);parseInt(a.dom.style.top)>b+16?(a.dom.style.top=parseInt(a.dom.style.top)-16+"px",a.uping=setTimeout(arguments.callee,5)):a.dom.style.top=b+"px"}}(E,j-E.height,d);if(!D)D=new CanvasLoader("main"),D.setColor("#59aceb"),
D.setShape("spiral"),D.setDiameter(83),D.setDensity(29),D.setFPS(27),k=document.getElementById("canvasLoader"),k.style.position="absolute",k.style.top=j+u.height/4-30+"px",k.style.left=(b[0]-c)/2+u.width/4-30+"px";D.show();H.style.top=document.getElementById("control_panel").offsetTop+31+"px";H.style.left=document.getElementById("control_panel").offsetLeft+28+"px";H.style.display="block";J.style.top=document.getElementById("control_panel").offsetTop+31+"px";J.style.left=document.getElementById("control_panel").offsetLeft+
251+"px";J.style.display="block";l.init({skin:a})}function g(b){function c(a){for(var b=a.top();b;)a.img[0]=b.img[0],a.img[1]=b.img[1],a.dropHeight+=a.height,a.animDrop(),a=b,b=a.top();a.dropHeight+=a.height;a.setImgIndex(Cell.getRandom());a.animDrop()}dropLock=!0;b.sort(function(a,b){return a.col-b.col});b.sort(function(a,b){return a.row-b.row});for(var d=0;d<b.length;d++)c(b[d]);setTimeout(function(){a.dropLock=!1},1E3)}function i(a,b,c){for(var d=0;d<a.length-1;d++)a[d].animStar();b?a[a.length-
1].animStar(b):a[a.length-1].animStar(function(b){return function(){setTimeout(function(){g(a);b()},100)}}(c))}function V(a,b,c){b?a.animBoom(b):a.animBoom(function(a){return function(){setTimeout(function(){g(cells);a()},100)}}(c))}function x(a,b,c){for(var d=0;d<a.length-1;d++)a[d].animBooming();b?a[a.length-1].animBooming(b):a[a.length-1].animBooming(function(b){return function(){setTimeout(function(){g(a);b()},100)}}(c))}function W(a,b,c){for(var d=0;d<a.length-1;d++)a[d].animBigboom();b?a[a.length-
1].animBigboom(b):a[a.length-1].animBigboom(function(b){return function(){setTimeout(function(){g(a);b()},100)}}(c))}function X(a,b){var c=!1;d.XMLHttpRequest?c=new XMLHttpRequest:d.ActiveXObject&&(c=new ActiveXObject("Microsoft.XMLHTTP"));if(c)c.open("GET","index.php?rankId="+a+"&rankValue="+b),c.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),c.onreadystatechange=function(){4==c.readyState&&200==c.status&&(ajaxData=eval("("+c.responseText+")"))},c.send("")}var l={},h=7,G=[],
m=[],L=[],A=6E4,p=0,Y=0;b={randomFresh:{time:5E3},deadDetect:{time:1E3},crab:{img:3,bouns:900,combo:8,count:document.getElementById("crab_count"),text:"一次炸9个呢，</br>快点使用吧!"},frog:{img:4,bouns:1200,combo:11,count:document.getElementById("frog_count"),text:"吃一竖排呢，</br>快点使用吧!"},elephant:{img:1,bouns:1200,combo:11,count:document.getElementById("elephant_count"),text:"吃一横排呢，</br>快点使用吧!"},chick:{img:5,bouns:1500,combo:14,count:document.getElementById("chick_count"),increase:1E4,text:"叽叽叽叽叽，</br>增加时间咯!"},
bat:{img:0,bouns:1500,combo:14,count:document.getElementById("bat_count"),text:"点谁谁就88，</br>快点使用吧!"},fox:{img:2,bouns:3E3,combo:24,count:document.getElementById("fox_count"),text:"神了炸好多，</br>快点使用吧!"},pig:{img:6,format:[[[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1]],[[6,1],,[6,1],,[6,1],,[6,1]],[[6,1],[6,1],,,,[6,1],[6,1]],[[6,1],,,,,,[6,1]],[[6,1],,[6,1],[6,1],[6,1],,[6,1]],[[6,1],,[6,1],,[6,1],,[6,1]],[[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1]]],bouns:3600,combo:35,count:document.getElementById("pig_count"),
text:"囧死你啊啊，</br>囧啊囧啊!"},panda:{img:7,bouns:4500,combo:44,count:document.getElementById("panda_count"),text:"全屏清除，</br>还加分!"}};a=function(){var a={},b={crab:{count:0,clear:0},frog:{count:0,clear:0},elephant:{count:0,clear:0},chick:{count:0,clear:0},bat:{count:0,clear:0},fox:{run:0,count:0,clear:0},pig:{count:0,clear:0},panda:{count:0,clear:0},randomFresh:{time:0},deadDetect:{time:0},toolAlerting:0,toolsEvent:[],toolsWarning:[],toolsEventIndex:0,toolsEventLock:!1,dropLock:!1,toolsEventAutoUnlock:null};
a.reStore=function(){for(var c in b)a[c]=JSON.parse(JSON.stringify(b[c]));return a};return a.reStore()}();var D,P=!0,I,H,J,M,O,E={dom:null,height:381,uping:null,downing:null},C,u,N,Q=!1,B,T=-1,U,K;l.init=function(a){var b=new PxLoader;Cell.imgArr=[];Cell.cells=[];for(var c=0;c<Cell.animalNum;c++){Cell.imgArr[c]=[];for(var d=1;1>=d;d++)Cell.imgArr[c][d]=b.addImage("img/"+a.skin+"/"+c+d+".png")}Cell.mouseImgArr=[];Cell.mouseImgArr[0]=b.addImage("img/mouse1.png");Cell.mouseImgArr[1]=b.addImage("img/mouse2.png");
Cell.mouseImgArr[2]=b.addImage("img/mouse3.png");Cell.mouseImgArr[3]=b.addImage("img/mouse4.png");Cell.mouseImgArr[4]=b.addImage("img/mouse5.png");Cell.mouseImgArr[5]=b.addImage("img/mouse6.png");Cell.mouseImgArr[6]=b.addImage("img/mouse7.png");Cell.mouseImgArr[7]=b.addImage("img/mouse8.png");Cell.starsArr=[];for(c=1;16>c;c++)Cell.starsArr[c]=b.addImage("img/stars/"+c+".png");Cell.boomArr=[b.addImage("img/boom/boom0.png"),b.addImage("img/boom/boom1.png")];Cell.boomingArr=[];for(c=0;7>c;c++)Cell.boomingArr[c]=
b.addImage("img/boom/booming"+c+".png");Cell.boomed=b.addImage("img/boom/boomed.png");Cell.bigboomArr=[b.addImage("img/boom/bigboom0.png"),b.addImage("img/boom/bigboom1.png")];Cell.disappearArr=[];for(c=0;11>c;c++)Cell.disappearArr[c]=b.addImage("img/disappear/"+c+".png");Cell.frogImgArr=[];Cell.frogImgArr[0]=b.addImage("img/mouse1.png");Cell.frogImgArr[1]=b.addImage("img/mouse2.png");Cell.frogImgArr[2]=b.addImage("img/mouse3.png");Cell.frogImgArr[3]=b.addImage("img/mouse4.png");Cell.frogImgArr[4]=
b.addImage("img/mouse5.png");Cell.frogImgArr[5]=b.addImage("img/mouse6.png");Cell.frogImgArr[6]=b.addImage("img/mouse7.png");Cell.frogImgArr[7]=b.addImage("img/mouse8.png");b.addCompletionListener(function(){console.log(B);D.hide();for(var a=0;a<h;a++){Cell.cells[a]=[];for(var b=0;b<h;b++)Cell.cells[a][b]=new Cell({img:[Cell.getRandom(),1],ctx:N,height:B,width:B,x:b*B,y:a*B,row:a,col:b}),Cell.cells[a][b].show()}l.reStart()});b.start()};l.stop=function(){document.getElementById("div_messagebox").style.display=
"none";document.getElementById("control_panel").style.opacity="1";this.stoped=!0};l.pause=function(){document.getElementById("div_messagebox").style.display="none";document.getElementById("control_panel").style.opacity="1";this.paused=!0};l.resume=function(){y();this.paused=!1};l.refresh=function(){for(var a,b,c=0;2>c;c++)a=parseInt(Math.random()*h,10),b=parseInt(Math.random()*h,10),a=Cell.cells[a][b],a.getLock()||(a.setImgIndex(Cell.getRandom()),a.setRedraw())};l.refreshAll=function(){for(var a=
Cell.cells.length,b=0;b<a;b++)for(var c=Cell.cells[b].length,d=0;d<c;d++)Cell.cells[b][d].setImgIndex(Cell.getRandom()),Cell.cells[b][d].setRedraw()};l.clearSameColor=function(b){for(var c=0,d=Cell.cells.length,e=[],f=0;f<d;f++)for(var h=Cell.cells[f].length,g=0;g<h;g++)Cell.cells[f][g].getImgIndex()===b.getImgIndex()&&(Cell.cells[f][g].getLock()||e.push(Cell.cells[f][g]),c++);i(e,null,function(){setTimeout(function(){a.toolsEventLock=!1},400)});p+=100*c};l.clearAll=function(){for(var a=Cell.cells.length,
b=0;b<a;b++)for(var c=Cell.cells[b].length,d=0;d<c;d++)Cell.cells[b][d].getLock()||Cell.cells[b][d].animScale()};l.reStart=function(){document.getElementById("div_messagebox").style.display="none";document.getElementById("control_panel").style.opacity="1";this.paused=!1;l.stop();(function(){var a=arguments.callee;d.setTimeout(function(){P?l.start():a.call(l)},100)})()};l.start=function(){G=[];this.paused=this.stoped=P=!1;t(A);R(0);p=0;a.reStore();A=6E4;var e=v(),f=new Date,i;e(function(j){j=j||new Date;
if(l.stoped&&!z())P=!0;else{i=j-f;if(32<=i){Y++;if(!l.paused){!a.toolsEventLock&&!a.dropLock&&(A-=i);0>=A&&(A=0,l.stop(),d.setTimeout(function(){r();X(1,p)},1500),t(A));a.randomFresh.time+=i;if(a.randomFresh.time>=b.randomFresh.time)a.randomFresh.time=0;a.deadDetect.time+=i;if(a.deadDetect.time>=b.deadDetect.time)t(A),a.deadDetect.time=0,n()&&w();(function(){for(var c in b){var d=b[c];if(d.count)d.count.innerHTML=a[c].clear}})();for(var k=G.pop();k&&k.cell;){c(m);if(!a.toolsEventLock&&a.toolsEventIndex<
a.toolsEvent.length&&!a.dropLock){a.toolsEventLock=!0;a.toolsEventAutoUnlock||clearTimeout(a.toolsEventAutoUnlock);a.toolsEventAutoUnlock=setTimeout(function(){a.toolsEventLock=!1},4E3);a.toolsEventIndex++;a.toolsEvent[a.toolsEventIndex-1](k,a);a.toolsEventIndex<a.toolsWarning.length?y():(document.getElementById("div_messagebox").style.display="none",document.getElementById("control_panel").style.opacity="1");break}else if(!a.toolsEventLock&&!a.dropLock){if(!k.cell.getLock()){var q=s(k.cell),k=q.length;
if(3<=k){if(6==q[0].img[0]&&15<q.length)a.pig.clear+=1;else for(o=0;o<k;o++)(function(){var c=q[o].img[0],d;for(d in b)b[d].img==c&&a[d].clear++})();a.fox.clear>b.fox.combo&&(a.fox.clear-=b.fox.combo,y(b.fox),a.toolsEvent.push(function(c){var d=s(c.cell),e=d.length;(function(){function a(c){for(var d=0;d<b.length;d++)if(b[d][0]==c[0]&&b[d][1]==c[1])return;b.push(c)}for(var b=[],c=0;c<e;c++){var f=d[c],g=f.col,f=f.row;a([f,g]);for(var j=-1;2>j;j++){var k=g+j;if(-1<k&&k<h)for(var i=-1;2>i;i++){var l=
f+i;-1<l&&l<h&&a([l,k])}}}d=[];for(g=0;g<b.length;g++)d.push(Cell.cells[b[g][0]][b[g][1]]);return b.length})();p+=b.fox.bouns;p+=100*e;W(d,null,function(){setTimeout(function(){a.toolsEventLock=!1},400)})}));if(10>k&&a.pig.clear>b.pig.combo)a.pig.clear-=b.pig.combo,F(b.pig),function(){for(var a=0;a<b.pig.format.length;a++)for(var c=0;c<b.pig.format[a].length;c++){var d=b.pig.format[a][c];d&&(Cell.cells[a][c].img[0]=d[0],Cell.cells[a][c].img[1]=d[1],Cell.cells[a][c].setRedraw())}}(),p+=b.pig.bouns;
else{for(var o=0;o<k-1;o++)a.toolsEventLock=!0,q[o].animDisappear();q[k-1].animDisappear(function(){g(q);setTimeout(function(){a.toolsEventLock=!1},400)});p+=100*k}}}break}k=G.pop()}R(p);a.crab.clear>b.crab.combo&&(a.crab.clear-=b.crab.combo,y(b.crab),a.toolsEvent.push(function(c){for(var d=[],e=c.cell.col,f=c.cell.row,g=Cell.cells.length,j=-1;2>j;j++){var h=e+j;if(-1<h&&h<g)for(var k=-1;2>k;k++){var i=f+k;-1<i&&i<g&&d.push(Cell.cells[i][h])}}V(c.cell,function(a,b,c){return function(){a(b,null,c)}}(x,
d,function(){setTimeout(function(){a.toolsEventLock=!1},400)}));p+=b.crab.bouns}));a.frog.clear>b.frog.combo&&(a.frog.clear-=b.frog.combo,y(b.frog),a.toolsEvent.push(function(c){Cell.cells[Cell.cells.length-1][c.cell.col].animMouse("top",function(){for(var b=[],c=0;c<Cell.cells.length;c++)b.push(Cell.cells[c][this.col]);g(b);setTimeout(function(){a.toolsEventLock=!1},400)});p+=100*h;p+=b.frog.bouns}));a.elephant.clear>b.elephant.combo&&(a.elephant.clear-=b.elephant.combo,y(b.elephant),a.toolsEvent.push(function(c){Cell.cells[c.cell.row][0].animMouse("right",
function(){g(Cell.cells[this.row]);setTimeout(function(){a.toolsEventLock=!1},400)});p+=100*h;p+=b.elephant.bouns}));a.bat.clear>b.bat.combo&&(a.bat.clear-=b.bat.combo,y(b.bat),a.toolsEvent.push(function(a){l.clearSameColor(a.cell);p+=b.bat.bouns}));a.chick.clear>b.chick.combo&&(a.chick.clear-=b.chick.combo,A=6E4<A+b.chick.increase?6E4:A+b.chick.increase,p+=b.chick.bouns,F(b.chick));a.panda.clear>b.panda.combo&&(F(b.panda),a.panda.clear-=b.panda.combo,l.clearAll(),p+=b.panda.bouns,p+=100*h*h);k=Cell.cells.length;
for(o=0;o<k;o++)for(var v=Cell.cells[o].length,u=0;u<v;u++)Cell.cells[o][u].update()}f=j}e(arguments.callee)}})};(function(){var b="mousedown";wyx.h5game.isEventSupported("touchstart")&&(b="touchstart");u=document.getElementById("canvas");H=document.getElementById("btn_pause");J=document.getElementById("div_timer");u.addEventListener(b,function(b){!Q&&!a.toolsEventLock&&(Q=!0,setTimeout(function(){Q=!1},200),l.paused||G.push({cell:f(o(b)),e:b}))},!1);H.addEventListener(b,function(){l.paused||(0<A&&
l.pause(),r(0<A))},!1);var c=document.getElementById("resume"),d=document.getElementById("restart"),g=document.getElementById("quit");c.addEventListener(b,function(){l.resume();K()},!1);d.addEventListener(b,function(){l.refreshAll();l.reStart();K()},!1);g.addEventListener(b,function(){try{K(),H.style.display="none",J.style.display="none",document.querySelector("header").style.display="none",document.getElementById("div_messagebox").style.display="none",document.getElementById("control_panel").style.opacity=
"1",document.getElementById("main").style.display="none",document.querySelector(".entrance").style.display="block",document.getElementById("div_screen").style.display="none"}catch(a){}},!1);C=document.getElementById("help_div");C.style.left=document.getElementById("mainMenu").offsetLeft+"px";C.style.top="0px";var c=document.getElementById("oneminute"),d=document.getElementById("night"),g=document.getElementById("about"),h=document.getElementById("help");c.addEventListener(b,function(){S();e("140150")},
!1);d.addEventListener(b,function(){S();e("night")},!1);g.addEventListener(b,function(){C.style.display="block";document.getElementById("help_div_about_us").style.display="block"},!1);h.addEventListener(b,function(){C.style.display="block";document.getElementById("help_div_0").style.display="block"},!1);document.getElementById("divScreenHelpBtn").addEventListener(b,function(){C.style.display="block";document.getElementById("help_div_0").style.display="block"},!1);if(!localStorage.notFristInit)localStorage.notFristInit=
!0,C.style.display="block",document.getElementById("help_div_0").style.display="block";document.getElementById("divScreenBodyHelpBtn").addEventListener(b,function(){C.style.display="block";document.getElementById("help_div_0").style.display="block"},!1);C.addEventListener(b,function(){if("block"==document.getElementById("help_div_0").style.display)document.getElementById("help_div_0").style.display="none",document.getElementById("help_div_1").style.display="block";else if("block"==document.getElementById("help_div_1").style.display||
"block"==document.getElementById("help_div_about_us").style.display||"block"==document.getElementById("help_div_ranking").style.display)C.style.display="none",document.getElementById("help_div_1").style.display="none",document.getElementById("help_div_about_us").style.display="none",document.getElementById("help_div_ranking").style.display="none"},!1)})();(function(a,b){a.style.background="url('img/light"+b+".png') no-repeat";setTimeout(function(a,b,c){return function(){a(b,1==c?2:1)}}(arguments.callee,
a,b),150)})(document.getElementById("div_messagebox"),1)})(window);
