var nilFn = function(){};
var KEYCODE_UP = 38;    //usefull keycode
var KEYCODE_DOWN = 40; //usefull keycode
var KEYCODE_LEFT = 37;  //usefull keycode
var KEYCODE_RIGHT = 39;     //usefull keycode
var KEYCODE_W = 87;         //usefull keycode
var KEYCODE_A = 65;         //usefull keycode
var KEYCODE_D = 68;         //usefull keycode
var KEYCODE_S = 83;         //usefull keycode